export const INITIAL_NAV_DATA = {
    "status": "success",
    "message": "Data entry details data.",
    "data": {
        "header": [
            {
                "dataentrY_ID": 0,
                "companY_ID": 0,
                "noB_ID": 5,
                "naturE_OF_BUSINESS": "Agriculture",
                "loB_ID": 18,
                "linE_OF_BUSINESS": "Fruits",
                "batcH_ID": 124,
                "batcH_NO": "B00129",
                "breeD_NAME": "Mix Dates",
                "templatE_NAME": "Date Farm Planing",
                "templatE_ID": 665,
                "locatioN_NAME": "Area 3 Farm",
                "postinG_DATE": "0001-01-01T00:00:00",
                "p_DATE": "02-Apr-2025",
                "agE_DAYS": 0,
                "agE_WEEK": 0,
                "openinG_QTY": 204,
                "starT_DATE": "0001-01-01T00:00:00",
                "s_DATE": "01-Apr-2026",
                "runninG_COST": 29508.05,
                "remaininG_QTY": 0,
                "status": "new",
                "createD_BY": 0,
                "currenT_LOCATION": null,
                "location": null,
                "entrY_FROM": null,
                "chK_in_lat": null,
                "chK_in_long": null,
                "enD_DATE": null,
                "remark": "",
                "batch_cost": 90678,
                "stage": null,
                "location_to": 0
            }
        ],
        "line": [
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 1,
                "parameteR_TYPE": "Consumption",
                "parameteR_ID": "2117",
                "parameteR_NAME": "Organic Sprays ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 55,
                "dataentrY_TYPE_ID": 412,
                "dataentrY_TYPE": "Sprays",
                "dataentrY_UOM": "MG/L",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "1",
                "f_END_DATE": "365",
                "iteM_NAME": "Neem Pure Oil - I-00216",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 39705,
                "livestock_flag": 0,
                "status": null,
                "stock": 7765,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "NA",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 1,
                "parameteR_TYPE": "Consumption",
                "parameteR_ID": "2118",
                "parameteR_NAME": "Organic Fertilisers ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 23,
                "dataentrY_TYPE_ID": 411,
                "dataentrY_TYPE": "Fertilisers",
                "dataentrY_UOM": "KG",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "Nitrogen - I-00207",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 39676,
                "livestock_flag": 0,
                "status": null,
                "stock": 9964,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "NA",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 1,
                "parameteR_TYPE": "Consumption",
                "parameteR_ID": "2118",
                "parameteR_NAME": "Organic Fertilisers ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 34,
                "dataentrY_TYPE_ID": 411,
                "dataentrY_TYPE": "Fertilisers",
                "dataentrY_UOM": "KG",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "NPK fertilizers - I-00205",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 39675,
                "livestock_flag": 0,
                "status": null,
                "stock": 967,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "NA",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 1,
                "parameteR_TYPE": "Consumption",
                "parameteR_ID": "2118",
                "parameteR_NAME": "Organic Fertilisers ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 23,
                "dataentrY_TYPE_ID": 411,
                "dataentrY_TYPE": "Fertilisers",
                "dataentrY_UOM": "KG",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "Phosphorus - I-00208",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 39677,
                "livestock_flag": 0,
                "status": null,
                "stock": 9856,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "NA",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 1,
                "parameteR_TYPE": "Consumption",
                "parameteR_ID": "2118",
                "parameteR_NAME": "Organic Fertilisers ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 234,
                "dataentrY_TYPE_ID": 411,
                "dataentrY_TYPE": "Fertilisers",
                "dataentrY_UOM": "KG",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "Potassium - I-00209",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 39678,
                "livestock_flag": 0,
                "status": null,
                "stock": 946,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "NA",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 4,
                "parameteR_TYPE": "Descriptive",
                "parameteR_ID": "2104",
                "parameteR_NAME": "Humidity Level",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 0,
                "dataentrY_TYPE_ID": 297,
                "dataentrY_TYPE": "Humidity",
                "dataentrY_UOM": "%",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 0,
                "livestock_flag": 0,
                "status": null,
                "stock": 0,
                "parameter_input_type": "input",
                "parameter_input_format": "decimal",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 4,
                "parameteR_TYPE": "Descriptive",
                "parameteR_ID": "2127",
                "parameteR_NAME": "Temprature",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 0,
                "dataentrY_TYPE_ID": 268,
                "dataentrY_TYPE": "Temperature",
                "dataentrY_UOM": "°C",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "100",
                "iteM_NAME": "",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 0,
                "livestock_flag": 0,
                "status": null,
                "stock": 0,
                "parameter_input_type": "input",
                "parameter_input_format": "decimal",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 4,
                "parameteR_TYPE": "Descriptive",
                "parameteR_ID": "2571",
                "parameteR_NAME": "Fruit Development Stage",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 0,
                "dataentrY_TYPE_ID": 566,
                "dataentrY_TYPE": "F Dev Stage",
                "dataentrY_UOM": "NA",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 0,
                "livestock_flag": 0,
                "status": null,
                "stock": 0,
                "parameter_input_type": "dropdown",
                "parameter_input_format": "Khalal 2,Kimri 1,Rutab 3,Tamar 4",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 4,
                "parameteR_TYPE": "Descriptive",
                "parameteR_ID": "2572",
                "parameteR_NAME": "Pest & Disease Management Check",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 0,
                "dataentrY_TYPE_ID": 418,
                "dataentrY_TYPE": "Disease",
                "dataentrY_UOM": "NA",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 0,
                "livestock_flag": 0,
                "status": null,
                "stock": 0,
                "parameter_input_type": "dropdown",
                "parameter_input_format": "Completed,WIP",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 4,
                "parameteR_TYPE": "Descriptive",
                "parameteR_ID": "2573",
                "parameteR_NAME": "Remove Dry Leaves ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 0,
                "dataentrY_TYPE_ID": 436,
                "dataentrY_TYPE": "Preparation",
                "dataentrY_UOM": "NA",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 0,
                "livestock_flag": 0,
                "status": null,
                "stock": 0,
                "parameter_input_type": "dropdown",
                "parameter_input_format": "Completed,WIP",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 2,
                "parameteR_TYPE": "Direct/Indirect Cost",
                "parameteR_ID": "2343",
                "parameteR_NAME": "Resource ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 0.45,
                "dataentrY_TYPE_ID": 327,
                "dataentrY_TYPE": "Labour Expense",
                "dataentrY_UOM": "HRS",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "Field Workers  - RC0001",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 45,
                "livestock_flag": 0,
                "status": null,
                "stock": 0,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 2,
                "parameteR_TYPE": "Direct/Indirect Cost",
                "parameteR_ID": "2343",
                "parameteR_NAME": "Resource ",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 1224,
                "dataentrY_TYPE_ID": 415,
                "dataentrY_TYPE": "Equipment",
                "dataentrY_UOM": "HRS",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "Water Dripper  - RC0014",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 71,
                "livestock_flag": 0,
                "status": null,
                "stock": 0,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 3,
                "parameteR_TYPE": "Output",
                "parameteR_ID": "2569",
                "parameteR_NAME": "Dates",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 720,
                "dataentrY_TYPE_ID": 573,
                "dataentrY_TYPE": "Barhi Dates",
                "dataentrY_UOM": "KG",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "Barhi Dates  - I-00203",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 39673,
                "livestock_flag": 0,
                "status": null,
                "stock": 167,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "NA",
                "jsoN_SRNO": "[]"
            },
            {
                "linE_ID": 0,
                "parameteR_TYPE_ID": 3,
                "parameteR_TYPE": "Output",
                "parameteR_ID": "2569",
                "parameteR_NAME": "Dates",
                "formulA_FLAG": "",
                "actuaL_VALUE": 0,
                "uniT_COST": 670,
                "dataentrY_TYPE_ID": 574,
                "dataentrY_TYPE": "Medjool Dates",
                "dataentrY_UOM": "KG",
                "occurrence": "Daily",
                "frequencY_START_DATE": 0,
                "frequencY_END_DATE": 0,
                "f_START_DATE": "0",
                "f_END_DATE": "365",
                "iteM_NAME": "Medjool  Dates - I-00202",
                "linE_AMOUNT": 0,
                "batch_ID": 0,
                "iteM_ID": 39672,
                "livestock_flag": 0,
                "status": null,
                "stock": 565,
                "parameter_input_type": "",
                "parameter_input_format": "",
                "parameter_input_value": "",
                "company_id": 275,
                "sub_location_id": 0,
                "consumptioN_MAP_ITEM": null,
                "livestock": [],
                "inventorY_TYPE": "NA",
                "jsoN_SRNO": "[]"
            }
        ],
        "livestock_new": []
    }
};
